# 교양필수 제외 나머지 수업 테이블 생성

1. 연장 준비

In [1]:
import pdfplumber as pp
import pandas as pd

In [2]:
o_pdf = pp.open('23-2.pdf')
o_pdf

2. 필요한 테이블 추출

In [3]:
o_df1 = [] #(pdf상)p6 ~ p7
o_df2 = [] #(pdf상)p8 ~ 끝까지

In [4]:
for pn in range(5, 7): #(pdf상)p6 ~ p7
    table_len = len(o_pdf.pages[pn].extract_tables())
    
    for tn in range(table_len):
        pre = o_pdf.pages[pn].extract_tables() 
        o_df1.append(pd.DataFrame(pre[tn])) #테이블 하나씩 데이터프레임으로 변환후 data에 담기
        
for pn in range(7, len(o_pdf.pages)): #(pdf상)p8 ~ 끝까지
    table_len = len(o_pdf.pages[pn].extract_tables())
    
    for tn in range(table_len):
        pre = o_pdf.pages[pn].extract_tables() 
        o_df2.append(pd.DataFrame(pre[tn])) #테이블 하나씩 데이터프레임으로 변환후 data에 담기

In [5]:
type(o_df1[0])

pandas.core.frame.DataFrame

In [6]:
print(len(o_df1), len(o_df2))

5 20

3. 필요한 열/행만 남기기

In [7]:
# o_df1 정리
o_df1[0]

,0,1,2,3,4,5,6,7,8,9,10
0,순번,이수\n구분,개설\n학년,과목코드,분반,교과목명,학점,교수명,학부\n제한,강의실/시간,확인사항
1,1,전탐,1,VH00002,01,일본의 이해,3,권혁태,N,7308 / 목 / 09:00~11:50,
2,2,전탐,1,VH00004,01,영미문학기행,3,조병은,N,7208 / 월 / 12:00~13:15\n7208 / 수 / 12:00~13:15,
3,3,전탐,1,VH00005,01,일본의 생활문화,3,장화경,N,7309 / 월 / 13:30~14:45\n7309 / 수 / 13:30~14:45,
4,4,전탐,1,VH00006,01,네이티브 일본어회화,3,요코야마 \n나호코,N,7309 / 화 / 13:30~14:45\n7309 / 목 / 13:30~14:45,
5,5,전탐,1,VH00008,01,English Pronunciation,3,김혜인,N,7308 / 화 / 13:30~14:45\n7308 / 목 / 13:30~14:45,
6,6,전탐,1,VH00009,01,키워드로 본 오늘의 중국,3,장영석,N,M301 / 화 / 13:30~14:45\nM301 / 목 / 13:30~14:45,
7,7,전탐,1,VH00010,01,쉽게 배우는 중국어,3,장엽,N,7309 / 월 / 16:30~17:45\n7309 / 수 / 16:30~17:45,
8,8,전탐,1,VH00012,01,수도원 기행,3,이주엽,N,M205 / 화 / 13:30~14:45\nM205 / 목 / 13:30~14:45,
9,9,전탐,1,VH00031,01,종교심리학,3,이주엽,N,7208 / 화 / 16:30~17:45\n7208 / 목 / 16:30~17:45,

In [8]:
o_df1[0] = o_df1[0].loc[:, [1,3,4,5,7,9]] # 첫 번째 테이블 제외한 나머지 인덱스0은 삭제

for tn in range(len(o_df1)-1):
    t = o_df1[tn+1].loc[:, [1,3,4,5,7,9]]
    o_df1[tn+1] = t.drop(t.index[0])
    
o_df1

[        1        3   4                      5           7  \
 0  이수\n구분     과목코드  분반                   교과목명         교수명
 1      전탐  VH00002  01                 일본의 이해         권혁태
 2      전탐  VH00004  01                 영미문학기행         조병은
 3      전탐  VH00005  01               일본의 생활문화         장화경
 4      전탐  VH00006  01             네이티브 일본어회화  요코야마 \n나호코
 5      전탐  VH00008  01  English Pronunciation         김혜인
 6      전탐  VH00009  01          키워드로 본 오늘의 중국         장영석
 7      전탐  VH00010  01             쉽게 배우는 중국어          장엽
 8      전탐  VH00012  01                 수도원 기행         이주엽
 9      전탐  VH00031  01                  종교심리학         이주엽

                                                 9
 0                                          강의실/시간
 1                          7308 / 목 / 09:00~11:50
 2  7208 / 월 / 12:00~13:15\n7208 / 수 / 12:00~13:15
 3  7309 / 월 / 13:30~14:45\n7309 / 수 / 13:30~14:45
 4  7309 / 화 / 13:30~14:45\n7309 / 목 / 13:30~14:45
 5  7308 / 화 / 13:30~14:45\n7308 / 목 / 13:30~14:45
 6  M301 / 화 / 13:30~14:45\nM301 / 목 / 13:30~14:45
 7  7309 / 월 / 16:30~17:45\n7309 / 수 / 16:30~17:45
 8  M205 / 화 / 13:30~14:45\nM205 / 목 / 13:30~14:45
 9  7208 / 화 / 16:30~17:45\n7208 / 목 / 16:30~17:45  ,
     1        3   4                     5    7  \
 1  전탐  VS00001  01           영상으로보는정치의세계  이지윤
 2  전탐  VS00002  01  헷갈리는 사회문제 깊이 \n들여다보기  박경태
 3  전탐  VS00007  01               사회학의 초대  조효제
 4  전탐  VS00009  01               정치학의 초대  윤석준
 5  전탐  VS00010  01               경제학의 초대  유철규
 6  전탐  VS00011  01                생활과 금융  최우석
 7  전탐  VS00012  01            경제환경과 기업경영   이웅
 8  전탐  VS00013  01               사회복지학개론  조남경

                                                 9
 1                          7207 / 화 / 09:00~11:50
 2                          7207 / 목 / 09:00~11:50
 3                          7208 / 월 / 09:00~11:50
 4  3502 / 화 / 13:30~14:45\n3502 / 목 / 13:30~14:45
 5  7206 / 월 / 13:30~14:45\n7206 / 수 / 13:30~14:45
 6  7309 / 화 / 15:00~16:15\n7309 / 목 / 15:00~16:15
 7                          7308 / 화 / 15:00~17:50
 8  7208 / 화 / 15:00~16:15\n7208 / 목 / 15:00~16:15  ,
     1        3   4                                 5    7  \
 1  전탐  VS00028  01  우리사는경제 어디서 왔을까 2 \n:'한국경제의역사적전개'  이상철
 2  전탐  VS00029  01                           사회복지와인권  양경은

                                                 9
 1                          7202 / 수 / 09:00~11:50
 2  7207 / 화 / 12:00~13:15\n7207 / 목 / 12:00~13:15  ,
     1        3   4                  5    7  \
 1  전탐  VD00004  01          디지털드로잉워크숍  이영아
 2  전탐  VM00002  01         커뮤니케이션의 이해  김서중
 3  전탐  VM00003  01         민주주의와 저널리즘  김서중
 4  전탐  VM00004  01  뉴미디어를 위한 아트 앤 테크닉  김대우

                                                 9
 1                          M401 / 목 / 09:00~11:50
 2                          7308 / 수 / 09:00~11:50
 3                          7208 / 목 / 09:00~11:50
 4  6403 / 월 / 13:30~14:45\n6403 / 수 / 13:30~14:45  ,
     1        3   4             5    7  \
 1  전탐  VI00002  01  Python 프로그래밍  박경호
 2  전탐  VI00002  02  Python 프로그래밍  이하규
 3  전탐  VI00002  03  Python 프로그래밍  홍성준
 4  전탐  VI00003  01    컴퓨터조립 및 활용  정인철
 5  전탐  VI00005  01       웹 개발 입문  이해신
 6  전탐  VI00005  02       웹 개발 입문  김선형
 7  전탐  VI00019  01      데이터기초수학1  이상윤
 8  전탐  VI00022  01          공업수학  윤명호
 9  전탐  XA00005  01      C++프로그래밍  김학수

                                                 9
 1                          6206 / 수 / 09:00~11:50
 2  6406 / 월 / 15:00~16:15\n6406 / 수 / 15:00~16:15
 3  6405 / 화 / 12:00~13:15\n6405 / 목 / 12:00~13:15
 4                          6406 / 목 / 09:00~11:50
 5                          6206 / 금 / 09:00~11:50
 6                          6206 / 금 / 12:00~14:50
 7  6405 / 월 / 15:00~16:15\n6405 / 수 / 15:00~16:15
 8                          M402 / 월 / 12:00~14:50
 9  6201 / 월 / 16:30~17:45\n6201 / 수 / 16:30~17:45  ]

4. 정리된 테이블 연결하기

In [9]:
df1 = o_df1.copy()

In [10]:
df1 = pd.concat(df1)

5. 정리 중인 테이블 헤더 지정

In [11]:
df1_column = df1.iloc[0]
df1 = df1[1:]
df1.columns = df1_column

In [12]:
t1 = df1.copy()
t1

,이수\n구분,과목코드,분반,교과목명,교수명,강의실/시간
1,전탐,VH00002,01,일본의 이해,권혁태,7308 / 목 / 09:00~11:50
2,전탐,VH00004,01,영미문학기행,조병은,7208 / 월 / 12:00~13:15\n7208 / 수 / 12:00~13:15
3,전탐,VH00005,01,일본의 생활문화,장화경,7309 / 월 / 13:30~14:45\n7309 / 수 / 13:30~14:45
4,전탐,VH00006,01,네이티브 일본어회화,요코야마 \n나호코,7309 / 화 / 13:30~14:45\n7309 / 목 / 13:30~14:45
5,전탐,VH00008,01,English Pronunciation,김혜인,7308 / 화 / 13:30~14:45\n7308 / 목 / 13:30~14:45
6,전탐,VH00009,01,키워드로 본 오늘의 중국,장영석,M301 / 화 / 13:30~14:45\nM301 / 목 / 13:30~14:45
7,전탐,VH00010,01,쉽게 배우는 중국어,장엽,7309 / 월 / 16:30~17:45\n7309 / 수 / 16:30~17:45
8,전탐,VH00012,01,수도원 기행,이주엽,M205 / 화 / 13:30~14:45\nM205 / 목 / 13:30~14:45
9,전탐,VH00031,01,종교심리학,이주엽,7208 / 화 / 16:30~17:45\n7208 / 목 / 16:30~17:45
1,전탐,VS00001,01,영상으로보는정치의세계,이지윤,7207 / 화 / 09:00~11:50
2,전탐,VS00002,01,헷갈리는 사회문제 깊이 \n들여다보기,박경태,7207 / 목 / 09:00~11:50
3,전탐,VS00007,01,사회학의 초대,조효제,7208 / 월 / 09:00~11:50
4,전탐,VS00009,01,정치학의 초대,윤석준,3502 / 화 / 13:30~14:45\n3502 / 목 / 13:30~14:45
5,전탐,VS00010,01,경제학의 초대,유철규,7206 / 월 / 13:30~14:45\n7206 / 수 / 13:30~14:45
6,전탐,VS00011,01,생활과 금융,최우석,7309 / 화 / 15:00~16:15\n7309 / 목 / 15:00~16:15
7,전탐,VS00012,01,경제환경과 기업경영,이웅,7308 / 화 / 15:00~17:50
8,전탐,VS00013,01,사회복지학개론,조남경,7208 / 화 / 15:00~16:15\n7208 / 목 / 15:00~16:15
1,전탐,VS00028,01,우리사는경제 어디서 왔을까 2 \n:'한국경제의역사적전개',이상철,7202 / 수 / 09:00~11:50
2,전탐,VS00029,01,사회복지와인권,양경은,7207 / 화 / 12:00~13:15\n7207 / 목 / 12:00~13:15
1,전탐,VD00004,01,디지털드로잉워크숍,이영아,M401 / 목 / 09:00~11:50
2,전탐,VM00002,01,커뮤니케이션의 이해,김서중,7308 / 수 / 09:00~11:50
3,전탐,VM00003,01,민주주의와 저널리즘,김서중,7208 / 목 / 09:00~11:50
4,전탐,VM00004,01,뉴미디어를 위한 아트 앤 테크닉,김대우,6403 / 월 / 13:30~14:45\n6403 / 수 / 13:30~14:45
1,전탐,VI00002,01,Python 프로그래밍,박경호,6206 / 수 / 09:00~11:50
2,전탐,VI00002,02,Python 프로그래밍,이하규,6406 / 월 / 15:00~16:15\n6406 / 수 / 15:00~16:15
3,전탐,VI00002,03,Python 프로그래밍,홍성준,6405 / 화 / 12:00~13:15\n6405 / 목 / 12:00~13:15
4,전탐,VI00003,01,컴퓨터조립 및 활용,정인철,6406 / 목 / 09:00~11:50
5,전탐,VI00005,01,웹 개발 입문,이해신,6206 / 금 / 09:00~11:50
6,전탐,VI00005,02,웹 개발 입문,김선형,6206 / 금 / 12:00~14:50
7,전탐,VI00019,01,데이터기초수학1,이상윤,6405 / 월 / 15:00~16:15\n6405 / 수 / 15:00~16:15
8,전탐,VI00022,01,공업수학,윤명호,M402 / 월 / 12:00~14:50
9,전탐,XA00005,01,C++프로그래밍,김학수,6201 / 월 / 16:30~17:45\n6201 / 수 / 16:30~17:45

+) o_df2도 o_df1과 똑같이 정리

In [13]:
# o_df2 정리
o_df2[0]

,0,1,2,3,4,5,6,7,8,9
0,순번,이수\n구분,개설\n학년,과목코드,분반,교과목명,학점,교수명,강의실/시간,확인사항
1,1,전선,"2,3,4",LA00035,01,종교와사회복지,3,노철래\n한지수,7304 / 목 / 09:00~11:50,기독교문화 + 사회복지학 융복합교과목
2,2,전선,"2,3,4",LA00036,01,그리스도교신학개론II,3,차보람,7301 / 월 / 12:00~14:50,
3,3,전선,"2,3,4",LA00037,01,과학과기독교의대화,3,김기석,7302 / 화 / 09:00~11:50,
4,4,전선,"2,3,4",MD00031,01,신학과정치학의만남,3,박은홍\n박태식,7204 / 목 / 12:00~14:50,정치학 + 기독교문화 융복합교과목
5,5,전선,"2,3,4",AD00105,01,온라인게임과종교적상징,3,김한나,7208 / 수 / 15:00~17:50,기독교문화전공자가 수강시 전공으로 인정

In [14]:
o_df2[0] = o_df2[0].loc[:, [1,3,4,5,7,8]] # 첫 번째 테이블 제외한 나머지 인덱스0은 삭제

for tn in range(len(o_df2)-1):
    t = o_df2[tn+1].loc[:, [1,3,4,5,7,8]]
    o_df2[tn+1] = t.drop(t.index[0])
    
o_df2

[        1        3   4            5         7                       8
 0  이수\n구분     과목코드  분반         교과목명       교수명                  강의실/시간
 1      전선  LA00035  01      종교와사회복지  노철래\n한지수  7304 / 목 / 09:00~11:50
 2      전선  LA00036  01  그리스도교신학개론II       차보람  7301 / 월 / 12:00~14:50
 3      전선  LA00037  01    과학과기독교의대화       김기석  7302 / 화 / 09:00~11:50
 4      전선  MD00031  01    신학과정치학의만남  박은홍\n박태식  7204 / 목 / 12:00~14:50
 5      전선  AD00105  01  온라인게임과종교적상징       김한나  7208 / 수 / 15:00~17:50,
      1        3   4                   5    7  \
 1   전선  LB00001  01        영화로 읽는 셰익스피어  박미정
 2   전필  LB00003  01              영어독서지도  김성찬
 3   전필  LB00004  01            영어문장이해II  김성찬
 4   전선  LB00005  01        영미문학: 자연과 인간  조병은
 5   전필  LB00006  01            미국문화와 사회  박미정
 6   전선  LB00007  01              영어다독II  김혜인
 7   전필  LB00008  01  영어 다의어 2: 알맹이와 껍데기  권용현
 8   전선  LB00009  01         영어로 읽는 한국 2  권용현
 9   전선  LB00010  01        영어교수법및학습법 II  김성찬
 10  전선  AD00039  01            서양문학의 흐름  조병은
 11  전필  LB00012  01              영미문학개론  박미정
 12  전선  LB00013  01         언어와 커뮤니케이션1  권용현
 13  전선  LB00026  01               영어발달사  김성찬
 14  전필  LB00027  01                영작문2  김혜인

                                                  8
 1   7206 / 월 / 12:00~13:15\n7206 / 수 / 12:00~13:15
 2                           7306 / 목 / 12:00~13:50
 3                           7308 / 화 / 09:00~11:50
 4                           1503 / 화 / 09:00~11:50
 5   M402 / 월 / 16:30~17:45\nM402 / 수 / 16:30~17:45
 6                           7302 / 금 / 12:00~14:50
 7                           7309 / 수 / 09:00~11:50
 8                           7202 / 화 / 09:00~11:50
 9   7205 / 화 / 16:30~17:45\n7205 / 목 / 16:30~17:45
 10  7206 / 월 / 15:00~16:15\n7206 / 수 / 15:00~16:15
 11  M407 / 월 / 15:00~16:15\nM407 / 수 / 15:00~16:15
 12                          7309 / 목 / 09:00~11:50
 13  7205 / 화 / 15:00~16:15\n7205 / 목 / 15:00~16:15
 14  7302 / 화 / 12:00~13:15\n7302 / 목 / 12:00~13:15  ,
      1        3   4            5           7  \
 1   전선  LC00001  01       세계와 일본         양기호
 2   전선  LC00002  01       스크린일본어  요코야마 \n나호코
 3   전선  LC00003  01  일본근현대문학의 이해         박은희
 4   전선  LC00004  01       일본근현대사         권혁태
 5   전선  LC00006  01      일본어표현연습  요코야마 \n나호코
 6   전선  LC00007  01     일본원서 강독2         권혁태
 7   전선  LC00008  01        일본정치론         양기호
 8   전선  LC00009  01        일본지방론         양기호
 9   전필  LC00010  01       일본학세미나         장화경
 10  전필  LC00011  01        일본학입문         장화경
 11  전선  LC00026  01  한일문화콘텐츠통번역2         박미숙

                                                  8
 1                           7303 / 화 / 09:00~11:50
 2   7303 / 화 / 12:00~13:15\n7303 / 목 / 12:00~13:15
 3                           7302 / 화 / 15:00~17:50
 4                           7301 / 화 / 09:00~11:50
 5   7303 / 월 / 13:30~14:45\n7303 / 수 / 13:30~14:45
 6   7301 / 화 / 13:30~14:45\n7301 / 목 / 13:30~14:45
 7   7303 / 화 / 13:30~14:45\n7303 / 목 / 13:30~14:45
 8                           7303 / 목 / 09:00~11:50
 9                           7302 / 수 / 09:00~11:50
 10  7302 / 월 / 12:00~13:15\n7302 / 수 / 12:00~13:15
 11                          7302 / 목 / 15:00~17:50  ,
     1        3   4          5    7  \
 1  전필  LD00002  01   중국고전을 읽다  백원담
 2  전선  LD00003  01     중국어회화Ⅲ   장엽
 3  전선  LD00004  01     중국문화산업  윤영도
 4  전선  LD00005  01    중국어 회화I   장엽
 5  전선  LD00006  01   중국의 경제정책  이남주
 6  전선  LD00008  01     한중번역연습  장영석
 7  전선  LD00009  01  중국어 작문 연습   장엽
 8  전필  LD00010  01     중국사회사정  장영석

                                                 8
 1  7307 / 월 / 15:00~16:15\n7307 / 수 / 15:00~16:15
 2  7306 / 월 / 13:30~14:45\n7306 / 수 / 13:30~14:45
 3  M403 / 화 / 12:00~13:15\nM403 / 목 / 12:00~13:15
 4  7302 / 화 / 13:30~14:45\n7302 / 목 / 13:30~14:45
 5  7305 / 화 / 15:00~16:15\n7305 / 목 / 15:00~16:15
 6  7305 / 화 / 16:30~17:45\n7305 / 목 / 16:30~17:45
 7                          7305 / 화 / 09:00~11:50
 8  7306 / 월 / 12:00~13:15\n7306 / 수 / 12:00~13:15  ,
      1        3   4           5    7  \
 1   전필  MA00001  01   인간행동과사회환경  김은영
 2   전필  MA00002  01     지역사회복지론  남일성
 3   전필  MA00003  01     사회복지조사론  김연아
 4   전필  MA00004  01     사회복지실천론  장희숙
 5   전필  MA00005  01   사회복지실천기술론  장희숙
 6   전필  MA00006  01     사회복지정책론  은민수
 7   전필  MA00007  01     사회복지행정론  황인매
 8   전필  MA00008  01   사회복지법제와실천  이호종
 9   전선  MA00009  01       아동복지론  양경은
 10  전선  MA00010  01       정신건강론  박지혜
 11  전선  MA00011  01       노인복지론  남일성
 12  전선  MA00012  01      장애인복지론  김용득
 13  전선  MA00014  01       복지국가론  문병주
 14  전선  MA00015  01   사회복지자료분석론  김형돈
 15  전필  MA00027  01  사회복지현장실습 I  서진환

                                                  8
 1                           7205 / 화 / 12:00~14:50
 2                           7205 / 목 / 09:00~11:50
 3                           M404 / 목 / 15:00~17:50
 4                           7304 / 수 / 12:00~14:50
 5                           7206 / 금 / 12:00~14:50
 6                           M407 / 월 / 12:00~14:50
 7                           M407 / 화 / 09:00~11:50
 8                           M407 / 화 / 15:00~17:50
 9   7207 / 화 / 13:30~14:45\n7207 / 목 / 13:30~14:45
 10                          7204 / 월 / 15:00~17:50
 11                          M406 / 화 / 09:00~11:50
 12                          7306 / 화 / 09:00~11:50
 13                          1506 / 수 / 15:00~17:50
 14                          3302 / 수 / 12:00~14:50
 15                          9999 / 토 / 09:00~11:50  ,
     1        3   4              5         7                       8
 1  전필  MA00027  02     사회복지현장실습 I       이동림  9999 / 토 / 09:00~11:50
 2  전선  MA00029  01          졸업세미나       양경은  7307 / 화 / 15:00~15:50
 3  전선  MA00033  01  융복합디지털사회복지혁신랩  이동림\n조남경  7417 / 수 / 15:00~17:50
 4  전선  MA00034  01  융복합미래사회복지실천실습  남일성\n이동림  7306 / 월 / 15:00~17:50
 5  전선  LA00035  01        종교와사회복지  노철래\n한지수  7304 / 목 / 09:00~11:50,
      1        3   4            5    7  \
 1   전선  MB00001  01       계급과 계층  김동춘
 2   전선  MB00003  01      사회이론의이해  조미혜
 3   전선  MB00004  01        젠더사회학  김향수
 4   전필  MB00006  01        사회학개론  조미혜
 5   전선  MB00008  01        역사사회학  오유석
 6   전선  MB00012  01      비교사회체제론  배성인
 7   전선  MB00017  01  사회과학방법론의 이해  김진업
 8   전선  MB00019  01      글로벌 사회학  조효제
 9   전선  MB00028  01    사회조사데이터분석  김이선
 10  전선  MB00030  01        교육과사회  박경주
 11  전선  MB00032  01      사회를위한경제  강영선
 12  전선  MB00037  01      인공지능과사회  정한별
 13  전선  AK00064  01      다양성과소수자  박경태

                                                  8
 1                           7306 / 화 / 15:00~17:50
 2                           1505 / 목 / 09:00~11:50
 3                           M406 / 수 / 15:00~17:50
 4                           7205 / 수 / 09:00~11:50
 5                           M402 / 화 / 15:00~17:50
 6                           M407 / 목 / 15:00~17:50
 7                           7204 / 수 / 12:00~14:50
 8                           7204 / 수 / 09:00~11:50
 9                           M401 / 화 / 12:00~14:50
 10                          1505 / 월 / 15:00~17:50
 11                          1505 / 화 / 09:00~11:50
 12                          M406 / 월 / 12:00~14:50
 13  7208 / 화 / 13:00~14:45\n7208 / 목 / 13:00~14:45  ,
     1        3   4             5    7  \
 1  전선  MC00001  01  거시경제학(국민소득론)  유철규
 2  전필  MC00002  01      경제학세미나 I  유철규
 3  전선  MC00003  01         문화경제학  신현준
 4  전선  MC00004  01           재정학  이상철
 5  전필  MC00005  01         경제학개론  유철규
 6  전선  MC00006  01       자본주의의역사  이상철
 7  전선  MC00007  01         노동경제학  신현준
 8  전선  MC00008  01     분배와복지의경제학  이동한

                                                 8
 1  7301 / 월 / 15:00~16:15\n7301 / 수 / 15:00~16:15
 2                          7304 / 월 / 09:00~11:50
 3  M404 / 월 / 13:30~14:45\nM404 / 수 / 13:30~14:45
 4  7305 / 화 / 13:30~14:45\n7305 / 목 / 13:30~14:45
 5  7301 / 화 / 16:30~17:45\n7301 / 목 / 16:30~17:45
 6                          7305 / 목 / 09:00~11:50
 7  M404 / 월 / 12:00~13:15\nM404 / 수 / 12:00~13:15
 8                          1506 / 화 / 09:00~11:50  ,
     1        3   4            5         7  \
 1  전필  MD00001  01        정치학개론       박은홍
 2  전선  MD00002  01       정당과 선거       김혜진
 3  전선  MD00006  01      현대한국정치론       김형철
 4  전선  MD00020  01  사회주의 체제와 북한       박은홍
 5  전선  MD00029  01       비교정치특강       박은홍
 6  전선  MD00030  01       국제개발협력       윤석준
 7  전선  MD00031  01    신학과정치학의만남  박은홍\n박태식

                                                 8
 1  M403 / 화 / 16:30~17:45\nM403 / 목 / 16:30~17:45
 2                          1506 / 수 / 12:00~14:50
 3                          1506 / 월 / 12:00~14:50
 4  7305 / 월 / 16:30~17:45\n7305 / 수 / 16:30~17:45
 5  7305 / 월 / 15:00~16:15\n7305 / 수 / 15:00~16:15
 6                          M404 / 화 / 09:00~11:50
 7                          7204 / 목 / 12:00~14:50  ,
      1        3   4            5         7  \
 1   전선  ME00002  01  글로벌비지니스의 이해       장승권
 2   전선  ME00002  02  글로벌비지니스의 이해       정은재
 3   전필  ME00003  01      경영정보시스템       송재민
 4   전선  ME00005  01       인적자원관리       윤숙희
 5   전선  ME00006  01       기업과 사회       윤길순
 6   전필  ME00007  01       기업재무관리       최우석
 7   전필  ME00009  01         경영전략       이선희
 8   전선  ME00010  01      경영의사결정론       박상선
 9   전필  ME00012  01          마케팅       이상훈
 10  전선  ME00014  01        셀프리더십       염준규
 11  전필  ME00017  01         조직행동  장승권\n정선영
 12  전선  ME00020  01  포트폴리오와 투자관리       최우석
 13  전선  ME00021  01         경영영어       조수미
 14  전선  ME00021  02         경영영어       조수미
 15  전선  ME00024  01       서비스 경영       이상훈
 16  전선  ME00027  01         경영회계       이동욱
 17  전선  ME00028  01  경영빅데이터프로그래밍       송재민

                                                  8
 1   M403 / 월 / 12:00~13:15\nM403 / 수 / 12:00~13:15
 2                           7304 / 월 / 15:00~17:50
 3                           7205 / 금 / 15:00~17:50
 4                           M402 / 수 / 09:00~11:50
 5                           M407 / 목 / 12:00~14:50
 6   7309 / 화 / 16:30~17:45\n7309 / 목 / 16:30~17:45
 7                           1505 / 목 / 15:00~17:50
 8   3302 / 화 / 12:00~13:15\n3302 / 목 / 12:00~13:15
 9                           7202 / 금 / 12:00~14:50
 10                          7204 / 월 / 12:00~14:50
 11                          7206 / 화 / 12:00~14:50
 12                          7204 / 금 / 12:00~14:50
 13                          M407 / 금 / 09:00~11:50
 14                          M406 / 금 / 12:00~14:50
 15                          7202 / 금 / 15:00~17:50
 16                          7306 / 수 / 15:00~17:50
 17  B105 / 월 / 13:30~14:45\nB105 / 수 / 13:30~14:45  ,
     1        3   4               5    7                       8
 1  전선  ME00029  01           팀창업실제  이예나  M403 / 금 / 09:00~11:50
 2  전선  ME00031  01      데이터분석방법론심화  미지정  M401 / 금 / 18:00~20:50
 3  전선  ME00032  01    머신러닝실습과팀프로젝트  미지정  7104 / 수 / 15:00~17:50
 4  전선  ME00033  01  빅데이터분석실습과팀프로젝트  미지정  M406 / 금 / 15:00~17:50
 5  전선  ME00034  01     빅데이터와비즈니스모델  미지정  M402 / 금 / 12:00~14:50,
      1        3   4            5    7  \
 1   전선  PB00001  01   스토리텔링과 미디어  백정숙
 2   전선  PB00002  01     사진커뮤니케이션  김서중
 3   전선  PB00003  01      미디어법과정책  김서중
 4   전필  PB00006  01      미디어조사방법  조은기
 5   전필  PB00008  01     기사작성과 편집  조도현
 6   전선  PB00009  01    저작권과지적재산권  김정훈
 7   전필  PB00010  01    스피치커뮤니케이션  최진봉
 8   전필  PB00010  02    스피치커뮤니케이션  최진봉
 9   전선  PB00011  01      PR캠페인실습  최진봉
 10  전선  PB00013  01     광고크리에이티브   윤목
 11  전선  PB00014  01    영상제작실습 II  연희승
 12  전선  PB00015  01     1인방송제작실습  연희승
 13  전선  PB00016  01    문화기획과예술경영  양재영
 14  전선  PB00017  01    연극과커뮤니케이션  권정택
 15  전선  PB00018  01      영상분석과비평  박소정
 16  전선  PB00019  01        광고캠페인  유은아
 17  전선  PB00020  01  소셜미디어와 시민사회  이진순
 18  전선  PB00043  01   커뮤니케이션 사상사  조은기

                                                  8
 1                           1503 / 화 / 15:00~17:50
 2                           7309 / 금 / 09:00~11:50
 3                           7204 / 화 / 09:00~11:50
 4                           7206 / 화 / 09:00~11:50
 5                           7202 / 목 / 09:00~11:50
 6                           7304 / 수 / 15:00~17:50
 7                           7204 / 월 / 09:00~11:50
 8                           7204 / 목 / 09:00~11:50
 9                           7205 / 금 / 12:00~14:50
 10                          1503 / 월 / 12:00~14:50
 11  M402 / 월 / 15:00~16:15\nM402 / 수 / 15:00~16:15
 12  B105 / 월 / 16:30~17:45\nB105 / 수 / 16:30~17:45
 13                          7202 / 목 / 15:00~17:50
 14                          7202 / 월 / 15:00~17:50
 15                          M402 / 수 / 12:00~14:50
 16                          7205 / 수 / 12:00~14:50
 17                          7204 / 화 / 12:00~14:50
 18                          7206 / 수 / 09:00~11:50  ,
     1        3   4                       5    7                       8
 1  전선  PB00044  01  4차 산업혁명과 디지털 미디어 \n플랫폼  조은기  7206 / 월 / 09:00~11:50
 2  전선  PD00001  01              문화기획의이론과실천  정윤수  7305 / 월 / 12:00~14:50
 3  전선  PD00002  01                미디어문화&사회  이정엽  1505 / 화 / 15:00~17:50,
      1        3   4                       5         7  \
 1   전선  PA00009  01                 디자인소재연구       이영아
 2   전선  PA00010  01                 영상디자인II       고일준
 3   전선  PA00012  01                   컨셉 아트       박인평
 4   전필  PA00021  01            디지털 라이팅과 랜더링       김대우
 5   전선  PA00028  01               일러스트 작품제작       박인평
 6   전선  PA00032  01                스토리보드 제작       김서윤
 7   전선  PA00033  01                 실험애니메이션       호중훈
 8   전필  PA00035  01                    게임제작       김대우
 9   전선  PA00039  01  영상에 활용하는 다이나믹 & 이펙트 효과       박은석
 10  전선  PA00041  01             3D캐릭터애니메이션2       박남기
 11  전선  PA00046  01                   인턴십II  박남기\n이영아
 12  전선  PA00048  01                디지털음악 II       현종찬
 13  전선  PA00053  01                 인턴십 세미나  박남기\n이영아
 14  전선  PA00054  01                   인턴십 I  박남기\n이영아
 15  전선  PC00002  01              콘텐츠프로듀싱실무론       곽미서
 16  전선  PC00006  01            코딩으로배우는미디어아트       김대우
 17  전선  PC00007  01             하드서페이스프랍모델링       김현근
 18  전필  PC00010  01                   3D모델링       신미현

                                                  8
 1                           M401 / 화 / 09:00~11:50
 2                           6403 / 수 / 15:00~17:50
 3                           M401 / 수 / 15:00~17:50
 4   6403 / 화 / 15:00~16:15\n6403 / 목 / 15:00~16:15
 5                           M401 / 수 / 12:00~14:50
 6                           M401 / 월 / 12:00~14:50
 7                           M401 / 화 / 15:00~17:50
 8                           M401 / 수 / 09:00~11:50
 9                           M401 / 금 / 09:00~11:50
 10                          6403 / 수 / 09:00~11:50
 11                          1407 / 토 / 09:00~17:50
 12                          6403 / 금 / 12:00~14:50
 13                          M201 / 화 / 18:00~18:50
 14                          1406 / 토 / 09:00~17:50
 15                          7208 / 금 / 09:00~11:50
 16  6403 / 화 / 16:30~17:45\n6403 / 목 / 16:30~17:45
 17                          6403 / 금 / 15:00~17:50
 18                          6403 / 목 / 12:00~14:50  ,
     1        3   4                  5    7                       8
 1  전선  PC00011  01        디지털미디어발상과표현  이종승  6110 / 금 / 15:00~17:50
 2  전필  PC00012  01           디지털이미지비평  박남기  M301 / 월 / 09:00~11:50
 3  전선  PC00014  01             기초게임엔진  박남기  6403 / 금 / 09:00~11:50
 4  전선  PC00015  01           뉴미디어와마케팅  김선구  7206 / 화 / 15:00~17:50
 5  전필  PC00021  01  캡스톤디자인-콘텐츠제작프로젝트2  박남기  7417 / 목 / 09:00~11:50
 6  전필  PC00021  02  캡스톤디자인-콘텐츠제작프로젝트2  이영아  6402 / 금 / 12:00~14:50
 7  전선  PC00024  01         모바일게임UI디자인  박선영  6403 / 화 / 12:00~14:50
 8  전선  PC00025  01         기초영상커뮤니케이션  곽미서  3402 / 수 / 09:00~11:50,
      1        3   4             5    7  \
 1   전필  XA00001  01         데이터통신  정연식
 2   전필  XA00002  01      신호 및 시스템  김학수
 3   전필  XA00003  01         컴퓨터구조  김학수
 4   전선  XA00005  01      C++프로그래밍  김학수
 5   전선  XA00006  01         과정지도2  임충규
 6   전선  XA00017  01  Python 프로그래밍  임충규
 7   전선  XA00019  01      모바일프로그래밍  정연식
 8   전선  XA00022  01    네트워크 프로그래밍  정연식
 9   전선  XA00023  01       게임프로그래밍  임충규
 10  전선  XA00025  01       디지털영상처리  김학수
 11  전선  XA00031  01         졸업지도2  김학수
 12  전필  XA00034  01   컴퓨터공학캡스톤디자인  김학수
 13  전선  XA00035  01    AR/VR시스템개발  임충규
 14  전필  XB00001  03          운영체제  박경호
 15  전선  XB00007  01          알고리즘  노은하

                                                  8
 1   M402 / 화 / 13:30~14:45\nM402 / 목 / 13:30~14:45
 2   6201 / 월 / 13:30~14:45\n6201 / 수 / 13:30~14:45
 3                           M402 / 화 / 09:00~11:50
 4   6201 / 월 / 16:30~17:45\n6201 / 수 / 16:30~17:45
 5                           6201 / 월 / 18:25~19:15
 6   6201 / 월 / 15:00~16:15\n6201 / 수 / 15:00~16:15
 7   6201 / 화 / 15:00~16:15\n6201 / 목 / 15:00~16:15
 8                           6201 / 수 / 09:00~11:50
 9   6109 / 월 / 13:30~14:45\n6109 / 수 / 13:30~14:45
 10  6109 / 월 / 15:00~16:15\n6109 / 수 / 15:00~16:15
 11                          6201 / 수 / 18:25~19:15
 12                          6109 / 월 / 09:00~11:50
 13                          6109 / 목 / 09:00~11:50
 14                          6202 / 금 / 12:00~14:50
 15                          6202 / 금 / 15:00~17:50  ,
      1        3   4             5    7  \
 1   전필  XB00001  01          운영체제  노은하
 2   전필  XB00001  02          운영체제  노은하
 3   전필  XB00001  03          운영체제  박경호
 4   전필  XB00002  01          자료구조  김명철
 5   전필  XB00002  02          자료구조  김명철
 6   전선  XB00004  01         컴퓨터구조  유상신
 7   전선  XB00005  01        데이터베이스  문성현
 8   전선  XB00006  01         데이터통신  유상신
 9   전필  XB00007  01          알고리즘  노은하
 10  전선  XB00008  01        웹프로그래밍  김선형
 11  전선  XB00008  02        웹프로그래밍  김선형
 12  전선  XB00013  01         사물인터넷  유상신
 13  전선  XB00015  01      프론트엔드 개발  이승진
 14  전선  XB00018  01    시스템분석 및 설계  문성현
 15  전선  XB00021  01  Python 프로그래밍  박경호
 16  전선  XB00024  01    네트워크 프로그래밍  이승진

                                                  8
 1   6201 / 화 / 12:00~13:15\n6201 / 목 / 12:00~13:15
 2   6201 / 화 / 13:30~14:45\n6201 / 목 / 13:30~14:45
 3                           6202 / 금 / 12:00~14:50
 4                           6206 / 화 / 09:00~11:50
 5                           6206 / 목 / 09:00~11:50
 6   M406 / 화 / 15:00~16:15\nM406 / 목 / 15:00~16:15
 7                           6201 / 금 / 09:00~11:50
 8   M406 / 화 / 16:30~17:45\nM406 / 목 / 16:30~17:45
 9                           6202 / 금 / 15:00~17:50
 10  6202 / 화 / 15:00~16:15\n6202 / 목 / 15:00~16:15
 11  6202 / 화 / 16:30~17:45\n6202 / 목 / 16:30~17:45
 12                          6406 / 화 / 09:00~11:50
 13  6202 / 월 / 13:30~14:45\n6202 / 수 / 13:30~14:45
 14                          6201 / 금 / 12:00~14:50
 15                          6202 / 금 / 09:00~11:50
 16  6202 / 월 / 12:00~13:15\n6202 / 수 / 12:00~13:15  ,
      1        3   4            5    7  \
 1   전선  XB00026  01    서버구축및형상관리  이승진
 2   전선  XB00027  01     백엔드프레임워크  이승진
 3   전선  XB00028  01    Java 프로젝트  문성현
 4   전선  XB00029  01  통계자료분석 및 실습  윤명호
 5   전선  XB00030  01      웹 개발 입문  이해신
 6   전선  XB00037  01    Java프로그래밍  김선형
 7   전선  XB00038  01   프론트엔드프레임워크  이승진
 8   전필  XC00028  01         졸업지도  김명철
 9   전선  XE00001  01      데이터분석입문  이상윤
 10  전선  XE00002  01         머신러닝  홍성준

                                                  8
 1                           6202 / 수 / 09:00~11:50
 2   6202 / 월 / 16:30~17:45\n6202 / 수 / 16:30~17:45
 3                           6201 / 금 / 15:00~17:50
 4                           M401 / 월 / 09:00~11:50
 5                           6202 / 목 / 09:00~11:50
 6   6202 / 화 / 13:30~14:45\n6202 / 목 / 13:30~14:45
 7   6202 / 월 / 15:00~16:15\n6202 / 수 / 15:00~16:15
 8                           6206 / 목 / 18:25~19:15
 9   6206 / 월 / 13:30~14:45\n6206 / 수 / 13:30~14:45
 10  6206 / 화 / 13:30~14:45\n6206 / 목 / 13:30~14:45  ,
      1        3   4           5    7  \
 1   전선  XC00003  01       데이터통신  박정식
 2   전선  XC00004  01     디지털회로실험  정인철
 3   전선  XC00005  01       사물인터넷  정인철
 4   전선  XC00006  01       컴퓨터구조  정인철
 5   전선  XC00022  01      웹프로그래밍  박정식
 6   전선  XC00023  01  네트워크 프로그래밍  박정식
 7   전선  XC00024  01    C++프로그래밍  이하규
 8   전선  XC00025  01     임베디드시스템  이종현
 9   전선  XC00026  01       인터넷보안  이종현
 10  전선  XC00027  01      TCP/IP  박정식
 11  전필  XC00028  01        졸업지도  김명철

In [15]:
df2 = o_df2.copy()

In [16]:
df2 = pd.concat(df2)

In [17]:
df2_column = df2.iloc[0]
df2 = df2[1:]
df2.columns = df2_column

In [18]:
t2 = df2.copy()
t2

,이수\n구분,과목코드,분반,교과목명,교수명,강의실/시간
1,전선,LA00035,01,종교와사회복지,노철래\n한지수,7304 / 목 / 09:00~11:50
2,전선,LA00036,01,그리스도교신학개론II,차보람,7301 / 월 / 12:00~14:50
3,전선,LA00037,01,과학과기독교의대화,김기석,7302 / 화 / 09:00~11:50
4,전선,MD00031,01,신학과정치학의만남,박은홍\n박태식,7204 / 목 / 12:00~14:50
5,전선,AD00105,01,온라인게임과종교적상징,김한나,7208 / 수 / 15:00~17:50
...,...,...,...,...,...,...
3,전선,XE00008,01,쉽게배우는스타트업창업,조준영,6110 / 목 / 16:00~17:50
4,전선,XE00009,01,심층신경망,홍성준,6405 / 목 / 09:00~11:50
5,전선,XE00010,01,오픈소스SW개발,이상윤,6405 / 월 / 16:30~17:45\n6405 / 수 / 16:30~17:45
6,전선,XE00011,01,인공지능문제해결,이상윤,6405 / 금 / 12:00~14:50
7,전선,XE00012,01,자료구조,홍성준,6405 / 화 / 09:00~11:50

6. 형식이 같아진 t1과 t2합치기 & 인덱스 초기화

In [19]:
t = pd.concat([t1, t2])

t.reset_index(drop=True, inplace=True)

t

,이수\n구분,과목코드,분반,교과목명,교수명,강의실/시간
0,전탐,VH00002,01,일본의 이해,권혁태,7308 / 목 / 09:00~11:50
1,전탐,VH00004,01,영미문학기행,조병은,7208 / 월 / 12:00~13:15\n7208 / 수 / 12:00~13:15
2,전탐,VH00005,01,일본의 생활문화,장화경,7309 / 월 / 13:30~14:45\n7309 / 수 / 13:30~14:45
3,전탐,VH00006,01,네이티브 일본어회화,요코야마 \n나호코,7309 / 화 / 13:30~14:45\n7309 / 목 / 13:30~14:45
4,전탐,VH00008,01,English Pronunciation,김혜인,7308 / 화 / 13:30~14:45\n7308 / 목 / 13:30~14:45
...,...,...,...,...,...,...
242,전선,XE00008,01,쉽게배우는스타트업창업,조준영,6110 / 목 / 16:00~17:50
243,전선,XE00009,01,심층신경망,홍성준,6405 / 목 / 09:00~11:50
244,전선,XE00010,01,오픈소스SW개발,이상윤,6405 / 월 / 16:30~17:45\n6405 / 수 / 16:30~17:45
245,전선,XE00011,01,인공지능문제해결,이상윤,6405 / 금 / 12:00~14:50
246,전선,XE00012,01,자료구조,홍성준,6405 / 화 / 09:00~11:50

# 바로 여기부터 ~~
열이름 변경해야하는데 데이터프레임이 아니라 튜플이네요.

6-2. 열이름 변경

In [63]:
print(type(t))
t.columns = ['kind','code','num','class_name','prof','room/time']
t

<class 'tuple'>

AttributeError: 'tuple' object has no attribute 'columns'

7. 전탐,전선 공동개설 수업의 중복 제거

In [59]:
m = t.copy()
#완전 중복 삭제
dup_m = m.drop_duplicates(subset=['이수\n구분','과목코드','분반','교과목명','교수명','강의실/시간'], keep='first', inplace=True, ignore_index=True)
#이수구분 다른 중복 수업 찾기
dup_m = m.duplicated(subset=['과목코드','분반','교과목명','교수명','강의실/시간'], keep=False) #중복되는 값 모두 True
dup_m

AttributeError: 'tuple' object has no attribute 'copy'

In [60]:
dup_m = pd.concat([m, dup_m], axis=1)
dup_m.rename(columns = {0 : 'dup_check'}, inplace = True)
dup_m

,이수\n구분,과목코드,분반,교과목명,교수명,강의실/시간,이수\n구분,과목코드,분반,교과목명,교수명,강의실/시간,dup_check
0,전탐,VH00002,01,일본의 이해,권혁태,7308 / 목 / 09:00~11:50,전탐,VH00002,01,일본의 이해,권혁태,7308 / 목 / 09:00~11:50,False
1,전탐,VH00004,01,영미문학기행,조병은,7208 / 월 / 12:00~13:15\n7208 / 수 / 12:00~13:15,전탐,VH00004,01,영미문학기행,조병은,7208 / 월 / 12:00~13:15\n7208 / 수 / 12:00~13:15,False
2,전탐,VH00005,01,일본의 생활문화,장화경,7309 / 월 / 13:30~14:45\n7309 / 수 / 13:30~14:45,전탐,VH00005,01,일본의 생활문화,장화경,7309 / 월 / 13:30~14:45\n7309 / 수 / 13:30~14:45,False
3,전탐,VH00006,01,네이티브 일본어회화,요코야마 \n나호코,7309 / 화 / 13:30~14:45\n7309 / 목 / 13:30~14:45,전탐,VH00006,01,네이티브 일본어회화,요코야마 \n나호코,7309 / 화 / 13:30~14:45\n7309 / 목 / 13:30~14:45,False
4,전탐,VH00008,01,English Pronunciation,김혜인,7308 / 화 / 13:30~14:45\n7308 / 목 / 13:30~14:45,전탐,VH00008,01,English Pronunciation,김혜인,7308 / 화 / 13:30~14:45\n7308 / 목 / 13:30~14:45,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,전선,XE00008,01,쉽게배우는스타트업창업,조준영,6110 / 목 / 16:00~17:50,전선,XE00008,01,쉽게배우는스타트업창업,조준영,6110 / 목 / 16:00~17:50,False
239,전선,XE00009,01,심층신경망,홍성준,6405 / 목 / 09:00~11:50,전선,XE00009,01,심층신경망,홍성준,6405 / 목 / 09:00~11:50,False
240,전선,XE00010,01,오픈소스SW개발,이상윤,6405 / 월 / 16:30~17:45\n6405 / 수 / 16:30~17:45,전선,XE00010,01,오픈소스SW개발,이상윤,6405 / 월 / 16:30~17:45\n6405 / 수 / 16:30~17:45,False
241,전선,XE00011,01,인공지능문제해결,이상윤,6405 / 금 / 12:00~14:50,전선,XE00011,01,인공지능문제해결,이상윤,6405 / 금 / 12:00~14:50,False
242,전선,XE00012,01,자료구조,홍성준,6405 / 화 / 09:00~11:50,전선,XE00012,01,자료구조,홍성준,6405 / 화 / 09:00~11:50,False

In [61]:
# 중복 추출
dup_class = dup_m['dup_check'] == True
dup = dup_m[dup_class]
dup

,이수\n구분,과목코드,분반,교과목명,교수명,강의실/시간,이수\n구분,과목코드,분반,교과목명,교수명,강의실/시간,dup_check
31,전탐,XA00005,01,C++프로그래밍,김학수,6201 / 월 / 16:30~17:45\n6201 / 수 / 16:30~17:45,전탐,XA00005,01,C++프로그래밍,김학수,6201 / 월 / 16:30~17:45\n6201 / 수 / 16:30~17:45,True
188,전선,XA00005,01,C++프로그래밍,김학수,6201 / 월 / 16:30~17:45\n6201 / 수 / 16:30~17:45,전선,XA00005,01,C++프로그래밍,김학수,6201 / 월 / 16:30~17:45\n6201 / 수 / 16:30~17:45,True
199,전선,XB00007,01,알고리즘,노은하,6202 / 금 / 15:00~17:50,전선,XB00007,01,알고리즘,노은하,6202 / 금 / 15:00~17:50,True
207,전필,XB00007,01,알고리즘,노은하,6202 / 금 / 15:00~17:50,전필,XB00007,01,알고리즘,노은하,6202 / 금 / 15:00~17:50,True
223,전선,XE00001,01,데이터분석입문,이상윤,6206 / 월 / 13:30~14:45\n6206 / 수 / 13:30~14:45,전선,XE00001,01,데이터분석입문,이상윤,6206 / 월 / 13:30~14:45\n6206 / 수 / 13:30~14:45,True
224,전선,XE00002,01,머신러닝,홍성준,6206 / 화 / 13:30~14:45\n6206 / 목 / 13:30~14:45,전선,XE00002,01,머신러닝,홍성준,6206 / 화 / 13:30~14:45\n6206 / 목 / 13:30~14:45,True
236,전필,XE00001,01,데이터분석입문,이상윤,6206 / 월 / 13:30~14:45\n6206 / 수 / 13:30~14:45,전필,XE00001,01,데이터분석입문,이상윤,6206 / 월 / 13:30~14:45\n6206 / 수 / 13:30~14:45,True
237,전필,XE00002,01,머신러닝,홍성준,6206 / 화 / 13:30~14:45\n6206 / 목 / 13:30~14:45,전필,XE00002,01,머신러닝,홍성준,6206 / 화 / 13:30~14:45\n6206 / 목 / 13:30~14:45,True

In [62]:
# 중복 수업 확인
dup_c = dup.copy()
# 과목코드 순 정렬
dup_c.sort_values('과목코드', inplace=True)
dup_c

ValueError: The column label '과목코드' is not unique.

In [ ]:
first = dup_c.iloc[0]['과목코드']
print(first)

In [ ]:
kind_list = []
v = ''

for index, row in dup_c.iterrows():
    if first == row.과목코드:
        if len(v)!=0:
            v += ', '
        v += row.'이수\n구분'
    else:
        kind_list.append(v)
        first = row.과목코드
        v = row.과목코드

In [ ]:
major